# Generated by Django 6.0.7 on 2026-07-23 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nifty_spot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nifty_change', models.DecimalField(decimal_places=2, max_digits=6)),
                ('banknifty_spot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('banknifty_change', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_pcr', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_signals', models.IntegerField(default=0)),
                ('buy_signals', models.IntegerField(default=0)),
                ('sell_signals', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('is_fno', models.BooleanField(default=True)),
                ('lot_size', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('grade', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C+', 'C+'), ('C', 'C'), ('D', 'D')], default='C', max_length=2)),
                ('signal_type', models.CharField(choices=[('BUY_NOW', 'Buy Now'), ('BUY', 'Buy'), ('WATCHLIST', 'Watchlist'), ('SELL', 'Sell'), ('AVOID', 'Avoid'), ('NEUTRAL', 'Neutral')], default='NEUTRAL', max_length=20)),
                ('option_type', models.CharField(choices=[('CE', 'CE'), ('PE', 'PE')], default='CE', max_length=2)),
                ('strike', models.IntegerField(default=0)),
                ('entry', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stop_loss', models.DecimalField(decimal_places=2, max_digits=12)),
                ('target_1', models.DecimalField(decimal_places=2, max_digits=12)),
                ('target_2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('target_3', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('risk_reward', models.CharField(blank=True, max_length=20)),
                ('confidence', models.IntegerField(default=0)),
                ('pcr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_pain', models.IntegerField(blank=True, null=True)),
                ('iv', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('oi_buildup', models.CharField(blank=True, max_length=100)),
                ('trend', models.CharField(default='NEUTRAL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('prediction_1d', models.DecimalField(blank=True, decimal_places=2, help_text='Predicted move % next day', max_digits=5, null=True)),
                ('prediction_3d', models.DecimalField(blank=True, decimal_places=2, help_text='Predicted move % next 3 days', max_digits=5, null=True)),
                ('prediction_confidence', models.IntegerField(default=0, help_text='Prediction model confidence')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='screener.stock')),
            ],
            options={
                'ordering': ['-score', '-created_at'],
                'indexes': [models.Index(fields=['-score', '-created_at'], name='screener_si_score_099797_idx'), models.Index(fields=['signal_type', '-created_at'], name='screener_si_signal__3bcfbb_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ltp', models.DecimalField(decimal_places=2, max_digits=12)),
                ('change_pct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('volume', models.BigIntegerField(default=0)),
                ('avg_volume', models.BigIntegerField(default=0)),
                ('rsi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('adx', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('macd', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('ema_20', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ema_50', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vwap', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='screener.stock')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['stock', '-timestamp'], name='screener_st_stock_i_d875f7_idx')],
            },
        ),
    ]
