from django.contrib import admin
from django.urls import path, include
from screener.views import (
    MarketDataView, SignalsView, TickerDataView,
    SniperOnlyView, StockDetailView, NewsView,
    MarketSummaryOldView, FoStockListOldView,
    FyersStatusView, OptionAnalyticsView, FyersBrowserTokenView, FyersDisconnectView,
    SignalExcelExportView, IndexTrackerView, IndexTrackerExportView,
    SignalExportDatesView, SignalExcelExportByDateView,
    IndexBacktestView, IndexBacktestExportView, WeeklyReportView,
    FundamentalsWatchlistView, CASAuctionMovesView, IndexTrackerAvailableDatesView,
    SignalWatchlistCsvView, IndexSignalView, CommodityCurrentSymbolView,
    DailyBacktestStatusView, DailyBacktestRunView, DailyBacktestReportDownloadView,
    DailyBacktestRangeView, FiftyTwoWeekRangeView, BroaderIndicesView,
    StrategyBacktestRunView, StrategyBacktestStatusView,
    DailyBacktestRangeReportView, SectorStocksView, NoTradeLogView,
    DataHealthView, TrendMomentumView, NextDayWatchlistView, RiskBudgetSettingsView,
    EODScanTriggerView, OptionHistoryView, CandleChartView,
)
from screener.cas_radar import CASRadarView
from screener.cas_research import CASResearchDatasetView
from screener.cas_readiness import CASReadinessView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/market-summary/', MarketSummaryOldView.as_view(), name='market_summary'),
    path('api/stocks/fo-list/', FoStockListOldView.as_view(), name='fo_stock_list'),
    path('api/market-data/', MarketDataView.as_view(), name='market_data'),
    path('api/signals/', SignalsView.as_view(), name='signals'),
    path('api/sniper-only/', SniperOnlyView.as_view(), name='sniper_only'),
    path('api/ticker/', TickerDataView.as_view(), name='ticker'),
    path('api/stock-detail/<str:symbol>/', StockDetailView.as_view(), name='stock_detail'),
    path('api/news/', NewsView.as_view(), name='news'),
    path('api/fyers-status/', FyersStatusView.as_view(), name='fyers_status'),
    path('api/fyers-disconnect/', FyersDisconnectView.as_view(), name='fyers_disconnect'),
    path('api/fyers-browser-token/', FyersBrowserTokenView.as_view(), name='fyers_browser_token'),
    path('api/option-analytics/<str:symbol>/', OptionAnalyticsView.as_view(), name='option_analytics'),
    path('api/signals/export/', SignalExcelExportView.as_view(), name='signals_export'),
    path('api/signals/export/dates/', SignalExportDatesView.as_view(), name='signals_export_dates'),
    path('api/signals/export/<str:date_str>/', SignalExcelExportByDateView.as_view(), name='signals_export_by_date'),
    path('api/signals/watchlist-csv/', SignalWatchlistCsvView.as_view(), name='signals_watchlist_csv'),
    path('api/index-tracker/<str:index_name>/', IndexTrackerView.as_view(), name='index_tracker'),
    path('api/trend-momentum/<str:index_name>/', TrendMomentumView.as_view(), name='trend_momentum'),
    path('api/next-day-watchlist/', NextDayWatchlistView.as_view(), name='next_day_watchlist'),
    path('api/settings/risk-budget/', RiskBudgetSettingsView.as_view(), name='risk_budget_settings'),
    path('api/next-day-watchlist/scan/', EODScanTriggerView.as_view(), name='eod_scan_trigger'),
    path('api/index-tracker/<str:index_name>/dates/', IndexTrackerAvailableDatesView.as_view(), name='index_tracker_dates'),
    path('api/index-tracker/<str:index_name>/export/', IndexTrackerExportView.as_view(), name='index_tracker_export'),
    path('api/index-backtest/<str:index_name>/', IndexBacktestView.as_view(), name='index_backtest'),
    path('api/index-backtest/<str:index_name>/export/', IndexBacktestExportView.as_view(), name='index_backtest_export'),
    path('api/weekly-report/', WeeklyReportView.as_view(), name='weekly_report'),
    path('api/fundamentals-watchlist/', FundamentalsWatchlistView.as_view(), name='fundamentals_watchlist'),
    path('api/cas-auction-moves/<str:index_name>/', CASAuctionMovesView.as_view(), name='cas_auction_moves'),
    path('api/cas-radar/<str:index_name>/', CASRadarView.as_view(), name='cas_radar'),
    path('api/cas-research/<str:index_name>/', CASResearchDatasetView.as_view(), name='cas_research'),
    path('api/cas-readiness/<str:index_name>/', CASReadinessView.as_view(), name='cas_readiness'),
    path('api/index-signals/', IndexSignalView.as_view(), name='index_signals'),
    path('api/commodity-symbol/<str:base_name>/', CommodityCurrentSymbolView.as_view(), name='commodity_symbol'),
    path('api/daily-backtest/status/', DailyBacktestStatusView.as_view(), name='daily_backtest_status'),
    path('api/daily-backtest/run/', DailyBacktestRunView.as_view(), name='daily_backtest_run'),
    path('api/daily-backtest/download/<str:report_type>/', DailyBacktestReportDownloadView.as_view(), name='daily_backtest_download'),
    path('api/daily-backtest/range/', DailyBacktestRangeView.as_view(), name='daily_backtest_range'),
    path('api/daily-backtest/range/report/', DailyBacktestRangeReportView.as_view(), name='daily_backtest_range_report'),
    path('api/52-week-range/<str:symbol>/', FiftyTwoWeekRangeView.as_view(), name='fifty_two_week_range'),
    path('api/broader-indices/', BroaderIndicesView.as_view(), name='broader_indices'),
    path('api/sector-stocks/<str:sector>/', SectorStocksView.as_view(), name='sector_stocks'),
    path('api/no-trade-log/', NoTradeLogView.as_view(), name='no_trade_log'),
    path('api/data-health/', DataHealthView.as_view(), name='data_health'),
    path('api/strategy-backtest/run/', StrategyBacktestRunView.as_view(), name='strategy_backtest_run'),
    path('api/strategy-backtest/status/', StrategyBacktestStatusView.as_view(), name='strategy_backtest_status'),
    path('api/option-history/', OptionHistoryView.as_view(), name='option_history'),
    path('api/candles/<str:symbol>/', CandleChartView.as_view(), name='candle_chart'),
    path('api/screener/', include('screener.urls')),
    path('api/options/', include('options.urls')),
    path('api/news/', include('news.urls')),
    path('api/trading/', include('trading.urls')),
    path('api/backtest/', include('backtest.urls')),
    path('api/fyers/', include('fyers_api.urls')),
]
